import { IdealTeamResponse } from '../../core/models/ideal-team.model';

/**
 * Hardcoded 4-3-3 ideal eleven matching the backend `IdealTeamResponseDto`
 * shape plus the FUT attributes the AI will emit. Used while the reveal
 * flow is built design-first; no endpoint is hit in this branch.
 *
 * x: 0=left → 1=right · y: 0=own goal → 1=rival goal.
 */
export const IDEAL_TEAM_MOCK: IdealTeamResponse = {
  formation: '4-3-3',
  goalkeeper: {
    id: 'gk-1',
    name: 'Thibaut Courtois',
    team: 'Real Madrid',
    position: 'GK',
    x: 0.5,
    y: 0.06,
    nationality: 'Bélgica',
    overall: 89,
    pac: 47,
    sho: 25,
    pas: 70,
    dri: 88,
    def: 49,
    phy: 88,
    reason:
      'Reflejos de élite y dominio del área. Aporta seguridad y un saque preciso para iniciar la jugada.',
  },
  defenders: [
    {
      id: 'lb-1',
      name: 'Theo Hernández',
      team: 'AC Milan',
      position: 'LB',
      x: 0.14,
      y: 0.26,
      nationality: 'Francia',
      overall: 85,
      pac: 94,
      sho: 71,
      pas: 80,
      dri: 84,
      def: 79,
      phy: 83,
      reason: 'Carril izquierdo con velocidad y llegada. Defiende y se suma al ataque.',
    },
    {
      id: 'cb-1',
      name: 'Rúben Dias',
      team: 'Manchester City',
      position: 'CB',
      x: 0.38,
      y: 0.2,
      nationality: 'Portugal',
      overall: 88,
      pac: 62,
      sho: 39,
      pas: 72,
      dri: 71,
      def: 89,
      phy: 88,
      reason: 'Líder defensivo, lectura impecable y salida limpia de balón.',
    },
    {
      id: 'cb-2',
      name: 'Virgil van Dijk',
      team: 'Liverpool',
      position: 'CB',
      x: 0.62,
      y: 0.2,
      nationality: 'Países Bajos',
      overall: 89,
      pac: 79,
      sho: 60,
      pas: 71,
      dri: 72,
      def: 90,
      phy: 86,
      reason: 'Físico dominante y anticipación. Ancla la línea y manda en el juego aéreo.',
    },
    {
      id: 'rb-1',
      name: 'Trent Alexander-Arnold',
      team: 'Real Madrid',
      position: 'RB',
      x: 0.86,
      y: 0.26,
      nationality: 'Inglaterra',
      overall: 86,
      pac: 76,
      sho: 72,
      pas: 90,
      dri: 80,
      def: 78,
      phy: 71,
      reason: 'Distribución de mediocampista desde la banda. Asiste y abre el campo.',
    },
  ],
  midfielders: [
    {
      id: 'cm-1',
      name: 'Kevin De Bruyne',
      team: 'Napoli',
      position: 'CM',
      x: 0.28,
      y: 0.5,
      nationality: 'Bélgica',
      overall: 91,
      pac: 72,
      sho: 88,
      pas: 93,
      dri: 87,
      def: 64,
      phy: 78,
      reason: 'El cerebro del equipo. Pase filtrado, disparo lejano y visión total.',
    },
    {
      id: 'cdm-1',
      name: 'Rodri',
      team: 'Manchester City',
      position: 'CDM',
      x: 0.5,
      y: 0.42,
      nationality: 'España',
      overall: 90,
      pac: 66,
      sho: 78,
      pas: 87,
      dri: 84,
      def: 87,
      phy: 85,
      reason: 'Ancla del medio campo. Recupera, ordena y dicta el ritmo.',
    },
    {
      id: 'cm-2',
      name: 'Jude Bellingham',
      team: 'Real Madrid',
      position: 'CM',
      x: 0.72,
      y: 0.5,
      nationality: 'Inglaterra',
      overall: 88,
      pac: 80,
      sho: 84,
      pas: 84,
      dri: 87,
      def: 78,
      phy: 84,
      reason: 'Box-to-box completo. Llega al área y aporta gol desde segunda línea.',
    },
  ],
  attackers: [
    {
      id: 'lw-1',
      name: 'Vinícius Júnior',
      team: 'Real Madrid',
      position: 'LW',
      x: 0.18,
      y: 0.78,
      nationality: 'Brasil',
      overall: 89,
      pac: 95,
      sho: 83,
      pas: 78,
      dri: 92,
      def: 29,
      phy: 68,
      reason: 'Desborde puro por la izquierda. Velocidad y regate para romper líneas.',
    },
    {
      id: 'st-1',
      name: 'Erling Haaland',
      team: 'Manchester City',
      position: 'ST',
      x: 0.5,
      y: 0.86,
      nationality: 'Noruega',
      overall: 91,
      pac: 89,
      sho: 93,
      pas: 66,
      dri: 80,
      def: 45,
      phy: 88,
      reason: 'Definición letal y presencia en el área. El referente goleador.',
    },
    {
      id: 'rw-1',
      name: 'Mohamed Salah',
      team: 'Liverpool',
      position: 'RW',
      x: 0.82,
      y: 0.78,
      nationality: 'Egipto',
      overall: 89,
      pac: 90,
      sho: 87,
      pas: 81,
      dri: 88,
      def: 45,
      phy: 75,
      reason: 'Diferencial por la derecha. Recorta hacia dentro y define con frialdad.',
    },
  ],
  generalJustification:
    'Un 4-3-3 equilibrado: defensa sólida con laterales que proyectan, un medio campo que combina recuperación (Rodri) y creación (De Bruyne, Bellingham), y un tridente ofensivo letal con desborde por bandas y un nueve de referencia.',
};
