/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    /**
     * FUT-style flippable player card — built for the "Equipo Ideal" feature.
     * Tap / click (or Enter / Space) flips the card on its vertical axis:
     *   - Front: tier-framed portrait, big overall, position, name, club and a
     *     compact 6-attribute strip — the classic Ultimate Team face.
     *   - Back:  the six attributes laid out as labelled gauges plus the AI's
     *     justification (`reason`) for picking this player.
     * Data-source agnostic by design: every value arrives through props, so the
     * host can feed it mock fixtures (this preview), a future stats-bearing
     * ideal-team response, or a per-player fetch — the component does not care.
     * Attributes are 0–99 (FUT scale), not the app's 0–10 statistic rating; the
     * AI is expected to emit them on the FUT scale. Tier (bronze / silver / gold
     * / icon) is derived from `overall` using FUT thresholds and drives the frame
     * colour, mirroring the ring tiers of <fma-player-card>.
     * Goalkeepers swap the outfield labels (PAC/SHO/PAS/DRI/DEF/PHY) for the GK
     * set (DIV/HAN/KIC/REF/SPD/POS) over the same six numeric slots.
     * Inherits --app-* design tokens through the shadow boundary with local
     * fallbacks, so it renders sensibly in a token-less host.
     */
    interface FmaFutCard {
        /**
          * Compact variant for the ideal-team pitch, where all 11 must fit on a phone. Drops the club, nationality and hint and shrinks the token so the front shows just overall + position + portrait + name; the back keeps the gauges (no justification). Tap still flips to reveal stats.
          * @default false
         */
        "compact": boolean;
        /**
          * Defending (outfield) / Speed (GK). 0–99.
         */
        "def"?: number;
        /**
          * Dribbling (outfield) / Reflexes (GK). 0–99.
         */
        "dri"?: number;
        /**
          * Flip state. Mutable so the host can drive it (e.g. flip the whole team at once) while taps still toggle it locally. Reflected to an attribute for easy CSS hooks from the host.
          * @default false
         */
        "flipped": boolean;
        /**
          * Player photo URL. Falls back to initials token when absent.
         */
        "imageUrl"?: string;
        /**
          * When true the card is keyboard-interactive and flips on activation. Set false for purely-decorative / externally-driven contexts.
          * @default true
         */
        "interactive": boolean;
        /**
          * Player display name (required).
         */
        "name": string;
        /**
          * Nationality label, shown small under the overall on the front.
         */
        "nationality"?: string;
        /**
          * Overall rating on the FUT 0–99 scale. Drives the tier / frame colour.
         */
        "overall"?: number;
        /**
          * Pace (outfield) / Diving (GK). 0–99.
         */
        "pac"?: number;
        /**
          * Passing (outfield) / Kicking (GK). 0–99.
         */
        "pas"?: number;
        /**
          * Physical (outfield) / Positioning (GK). 0–99.
         */
        "phy"?: number;
        /**
          * Fine-grained position from the ideal-team response (GK, CB, ST, CAM…). Shown verbatim on the front. A leading "GK" switches the back labels to the goalkeeper set.
         */
        "position"?: string;
        /**
          * Gemini's justification for picking this player — shown on the back.
         */
        "reason"?: string;
        /**
          * Shooting (outfield) / Handling (GK). 0–99.
         */
        "sho"?: number;
        /**
          * Club / team name.
         */
        "team"?: string;
    }
    /**
     * Player roster tile — used in /players list and search results.
     * Inputs map 1:1 to PlayerListItemDto from the .NET backend (and the
     * mirrored Node response): name, team, league, position, image-url,
     * rating. Anonymous and registered users see the same tile; admin
     * action affordances are exposed through the `actions` slot so this
     * component stays role-agnostic.
     * Clicking the tile emits a `playerSelected` CustomEvent with the
     * normalized payload, so the host can route to the detail page or
     * trigger any other navigation without the tile knowing about it.
     * Layout — square-ish tile (~1 : 1.15 aspect), designed for 2 columns
     * on a 360-420px mobile viewport and 3-5 columns on tablet/desktop via
     * `repeat(auto-fill, minmax(180px, 1fr))` on the host grid.
     * Design language ("Stadium control room HUD", Gridiron Neon palette
     * from DESIGN.md / frontend theme/variables.scss):
     *   - Circular player tokens with multi-layer glowing rings (ring color
     *     signals tier — bronze / silver / gold / icon) sit at the top.
     *   - Rating badge orbits the token at the 4-5 o'clock position.
     *   - Hexagonal grid backdrop + radial tier glow concentrated on the
     *     token area give the surface a premium simulator depth.
     *   - A thin tier accent stripe at the bottom edge reinforces the tier
     *     when the user scrolls a long grid.
     *   - The component reads --app-* CSS custom properties from the host
     *     so the design tokens are inherited automatically through the
     *     shadow boundary; no token duplication.
     * `league` is kept on the prop surface for forward-compat with the DTO
     * but intentionally not rendered in the tile — at 180px wide there is
     * no room for it without truncating something more important. The
     * league is still available on the player detail page.
     */
    interface FmaPlayerCard {
        /**
          * Image URL — Firebase Storage, API-Football, or manual.
         */
        "imageUrl"?: string;
        /**
          * When true, the whole tile is keyboard-interactive and emits playerSelected on click / Enter / Space. Defaults to true; flip to false for purely-display contexts (e.g. inside a pop-up).
          * @default true
         */
        "interactive": boolean;
        /**
          * Marks the tile as a manually-created player (no upstream API-Football source, therefore no statistics). When true, the rating slot is replaced by a "MANUAL" chip so users can tell the card apart from an imported player whose stats just haven't loaded yet.
          * @default false
         */
        "isManual": boolean;
        /**
          * League name. Accepted for DTO parity, not displayed in the tile.
         */
        "league"?: string;
        /**
          * Player display name (required).
         */
        "name": string;
        /**
          * Player identifier — emitted with playerSelected for the host to route.
         */
        "playerId"?: string;
        /**
          * Position label (Goalkeeper, Defender, Midfielder, Attacker).
         */
        "position"?: string;
        /**
          * Overall rating (0–10, decimal). Renders the orbital badge if present.
         */
        "rating"?: number;
        /**
          * Team name (required).
         */
        "team": string;
    }
}
export interface FmaFutCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFmaFutCardElement;
}
export interface FmaPlayerCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFmaPlayerCardElement;
}
declare global {
    interface HTMLFmaFutCardElementEventMap {
        "flipChange": { name: string; flipped: boolean };
    }
    /**
     * FUT-style flippable player card — built for the "Equipo Ideal" feature.
     * Tap / click (or Enter / Space) flips the card on its vertical axis:
     *   - Front: tier-framed portrait, big overall, position, name, club and a
     *     compact 6-attribute strip — the classic Ultimate Team face.
     *   - Back:  the six attributes laid out as labelled gauges plus the AI's
     *     justification (`reason`) for picking this player.
     * Data-source agnostic by design: every value arrives through props, so the
     * host can feed it mock fixtures (this preview), a future stats-bearing
     * ideal-team response, or a per-player fetch — the component does not care.
     * Attributes are 0–99 (FUT scale), not the app's 0–10 statistic rating; the
     * AI is expected to emit them on the FUT scale. Tier (bronze / silver / gold
     * / icon) is derived from `overall` using FUT thresholds and drives the frame
     * colour, mirroring the ring tiers of <fma-player-card>.
     * Goalkeepers swap the outfield labels (PAC/SHO/PAS/DRI/DEF/PHY) for the GK
     * set (DIV/HAN/KIC/REF/SPD/POS) over the same six numeric slots.
     * Inherits --app-* design tokens through the shadow boundary with local
     * fallbacks, so it renders sensibly in a token-less host.
     */
    interface HTMLFmaFutCardElement extends Components.FmaFutCard, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFmaFutCardElementEventMap>(type: K, listener: (this: HTMLFmaFutCardElement, ev: FmaFutCardCustomEvent<HTMLFmaFutCardElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFmaFutCardElementEventMap>(type: K, listener: (this: HTMLFmaFutCardElement, ev: FmaFutCardCustomEvent<HTMLFmaFutCardElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFmaFutCardElement: {
        prototype: HTMLFmaFutCardElement;
        new (): HTMLFmaFutCardElement;
    };
    interface HTMLFmaPlayerCardElementEventMap {
        "playerSelected": { playerId?: string; name: string };
    }
    /**
     * Player roster tile — used in /players list and search results.
     * Inputs map 1:1 to PlayerListItemDto from the .NET backend (and the
     * mirrored Node response): name, team, league, position, image-url,
     * rating. Anonymous and registered users see the same tile; admin
     * action affordances are exposed through the `actions` slot so this
     * component stays role-agnostic.
     * Clicking the tile emits a `playerSelected` CustomEvent with the
     * normalized payload, so the host can route to the detail page or
     * trigger any other navigation without the tile knowing about it.
     * Layout — square-ish tile (~1 : 1.15 aspect), designed for 2 columns
     * on a 360-420px mobile viewport and 3-5 columns on tablet/desktop via
     * `repeat(auto-fill, minmax(180px, 1fr))` on the host grid.
     * Design language ("Stadium control room HUD", Gridiron Neon palette
     * from DESIGN.md / frontend theme/variables.scss):
     *   - Circular player tokens with multi-layer glowing rings (ring color
     *     signals tier — bronze / silver / gold / icon) sit at the top.
     *   - Rating badge orbits the token at the 4-5 o'clock position.
     *   - Hexagonal grid backdrop + radial tier glow concentrated on the
     *     token area give the surface a premium simulator depth.
     *   - A thin tier accent stripe at the bottom edge reinforces the tier
     *     when the user scrolls a long grid.
     *   - The component reads --app-* CSS custom properties from the host
     *     so the design tokens are inherited automatically through the
     *     shadow boundary; no token duplication.
     * `league` is kept on the prop surface for forward-compat with the DTO
     * but intentionally not rendered in the tile — at 180px wide there is
     * no room for it without truncating something more important. The
     * league is still available on the player detail page.
     */
    interface HTMLFmaPlayerCardElement extends Components.FmaPlayerCard, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFmaPlayerCardElementEventMap>(type: K, listener: (this: HTMLFmaPlayerCardElement, ev: FmaPlayerCardCustomEvent<HTMLFmaPlayerCardElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFmaPlayerCardElementEventMap>(type: K, listener: (this: HTMLFmaPlayerCardElement, ev: FmaPlayerCardCustomEvent<HTMLFmaPlayerCardElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFmaPlayerCardElement: {
        prototype: HTMLFmaPlayerCardElement;
        new (): HTMLFmaPlayerCardElement;
    };
    interface HTMLElementTagNameMap {
        "fma-fut-card": HTMLFmaFutCardElement;
        "fma-player-card": HTMLFmaPlayerCardElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}` | `prop:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K | `prop:${K}`]?: never } | { [P in `prop:${K}`]: PropT } & { [P in K | `attr:${K}`]?: never };

    /**
     * FUT-style flippable player card — built for the "Equipo Ideal" feature.
     * Tap / click (or Enter / Space) flips the card on its vertical axis:
     *   - Front: tier-framed portrait, big overall, position, name, club and a
     *     compact 6-attribute strip — the classic Ultimate Team face.
     *   - Back:  the six attributes laid out as labelled gauges plus the AI's
     *     justification (`reason`) for picking this player.
     * Data-source agnostic by design: every value arrives through props, so the
     * host can feed it mock fixtures (this preview), a future stats-bearing
     * ideal-team response, or a per-player fetch — the component does not care.
     * Attributes are 0–99 (FUT scale), not the app's 0–10 statistic rating; the
     * AI is expected to emit them on the FUT scale. Tier (bronze / silver / gold
     * / icon) is derived from `overall` using FUT thresholds and drives the frame
     * colour, mirroring the ring tiers of <fma-player-card>.
     * Goalkeepers swap the outfield labels (PAC/SHO/PAS/DRI/DEF/PHY) for the GK
     * set (DIV/HAN/KIC/REF/SPD/POS) over the same six numeric slots.
     * Inherits --app-* design tokens through the shadow boundary with local
     * fallbacks, so it renders sensibly in a token-less host.
     */
    interface FmaFutCard {
        /**
          * Compact variant for the ideal-team pitch, where all 11 must fit on a phone. Drops the club, nationality and hint and shrinks the token so the front shows just overall + position + portrait + name; the back keeps the gauges (no justification). Tap still flips to reveal stats.
          * @default false
         */
        "compact"?: boolean;
        /**
          * Defending (outfield) / Speed (GK). 0–99.
         */
        "def"?: number;
        /**
          * Dribbling (outfield) / Reflexes (GK). 0–99.
         */
        "dri"?: number;
        /**
          * Flip state. Mutable so the host can drive it (e.g. flip the whole team at once) while taps still toggle it locally. Reflected to an attribute for easy CSS hooks from the host.
          * @default false
         */
        "flipped"?: boolean;
        /**
          * Player photo URL. Falls back to initials token when absent.
         */
        "imageUrl"?: string;
        /**
          * When true the card is keyboard-interactive and flips on activation. Set false for purely-decorative / externally-driven contexts.
          * @default true
         */
        "interactive"?: boolean;
        /**
          * Player display name (required).
         */
        "name": string;
        /**
          * Nationality label, shown small under the overall on the front.
         */
        "nationality"?: string;
        /**
          * Emits the new flip state whenever the card turns.
         */
        "onFlipChange"?: (event: FmaFutCardCustomEvent<{ name: string; flipped: boolean }>) => void;
        /**
          * Overall rating on the FUT 0–99 scale. Drives the tier / frame colour.
         */
        "overall"?: number;
        /**
          * Pace (outfield) / Diving (GK). 0–99.
         */
        "pac"?: number;
        /**
          * Passing (outfield) / Kicking (GK). 0–99.
         */
        "pas"?: number;
        /**
          * Physical (outfield) / Positioning (GK). 0–99.
         */
        "phy"?: number;
        /**
          * Fine-grained position from the ideal-team response (GK, CB, ST, CAM…). Shown verbatim on the front. A leading "GK" switches the back labels to the goalkeeper set.
         */
        "position"?: string;
        /**
          * Gemini's justification for picking this player — shown on the back.
         */
        "reason"?: string;
        /**
          * Shooting (outfield) / Handling (GK). 0–99.
         */
        "sho"?: number;
        /**
          * Club / team name.
         */
        "team"?: string;
    }
    /**
     * Player roster tile — used in /players list and search results.
     * Inputs map 1:1 to PlayerListItemDto from the .NET backend (and the
     * mirrored Node response): name, team, league, position, image-url,
     * rating. Anonymous and registered users see the same tile; admin
     * action affordances are exposed through the `actions` slot so this
     * component stays role-agnostic.
     * Clicking the tile emits a `playerSelected` CustomEvent with the
     * normalized payload, so the host can route to the detail page or
     * trigger any other navigation without the tile knowing about it.
     * Layout — square-ish tile (~1 : 1.15 aspect), designed for 2 columns
     * on a 360-420px mobile viewport and 3-5 columns on tablet/desktop via
     * `repeat(auto-fill, minmax(180px, 1fr))` on the host grid.
     * Design language ("Stadium control room HUD", Gridiron Neon palette
     * from DESIGN.md / frontend theme/variables.scss):
     *   - Circular player tokens with multi-layer glowing rings (ring color
     *     signals tier — bronze / silver / gold / icon) sit at the top.
     *   - Rating badge orbits the token at the 4-5 o'clock position.
     *   - Hexagonal grid backdrop + radial tier glow concentrated on the
     *     token area give the surface a premium simulator depth.
     *   - A thin tier accent stripe at the bottom edge reinforces the tier
     *     when the user scrolls a long grid.
     *   - The component reads --app-* CSS custom properties from the host
     *     so the design tokens are inherited automatically through the
     *     shadow boundary; no token duplication.
     * `league` is kept on the prop surface for forward-compat with the DTO
     * but intentionally not rendered in the tile — at 180px wide there is
     * no room for it without truncating something more important. The
     * league is still available on the player detail page.
     */
    interface FmaPlayerCard {
        /**
          * Image URL — Firebase Storage, API-Football, or manual.
         */
        "imageUrl"?: string;
        /**
          * When true, the whole tile is keyboard-interactive and emits playerSelected on click / Enter / Space. Defaults to true; flip to false for purely-display contexts (e.g. inside a pop-up).
          * @default true
         */
        "interactive"?: boolean;
        /**
          * Marks the tile as a manually-created player (no upstream API-Football source, therefore no statistics). When true, the rating slot is replaced by a "MANUAL" chip so users can tell the card apart from an imported player whose stats just haven't loaded yet.
          * @default false
         */
        "isManual"?: boolean;
        /**
          * League name. Accepted for DTO parity, not displayed in the tile.
         */
        "league"?: string;
        /**
          * Player display name (required).
         */
        "name": string;
        "onPlayerSelected"?: (event: FmaPlayerCardCustomEvent<{ playerId?: string; name: string }>) => void;
        /**
          * Player identifier — emitted with playerSelected for the host to route.
         */
        "playerId"?: string;
        /**
          * Position label (Goalkeeper, Defender, Midfielder, Attacker).
         */
        "position"?: string;
        /**
          * Overall rating (0–10, decimal). Renders the orbital badge if present.
         */
        "rating"?: number;
        /**
          * Team name (required).
         */
        "team": string;
    }

    interface FmaFutCardAttributes {
        "name": string;
        "team": string;
        "position": string;
        "imageUrl": string;
        "nationality": string;
        "overall": number;
        "pac": number;
        "sho": number;
        "pas": number;
        "dri": number;
        "def": number;
        "phy": number;
        "reason": string;
        "flipped": boolean;
        "interactive": boolean;
        "compact": boolean;
    }
    interface FmaPlayerCardAttributes {
        "name": string;
        "team": string;
        "league": string;
        "position": string;
        "imageUrl": string;
        "rating": number;
        "playerId": string;
        "isManual": boolean;
        "interactive": boolean;
    }

    interface IntrinsicElements {
        "fma-fut-card": Omit<FmaFutCard, keyof FmaFutCardAttributes> & { [K in keyof FmaFutCard & keyof FmaFutCardAttributes]?: FmaFutCard[K] } & { [K in keyof FmaFutCard & keyof FmaFutCardAttributes as `attr:${K}`]?: FmaFutCardAttributes[K] } & { [K in keyof FmaFutCard & keyof FmaFutCardAttributes as `prop:${K}`]?: FmaFutCard[K] } & OneOf<"name", FmaFutCard["name"], FmaFutCardAttributes["name"]>;
        "fma-player-card": Omit<FmaPlayerCard, keyof FmaPlayerCardAttributes> & { [K in keyof FmaPlayerCard & keyof FmaPlayerCardAttributes]?: FmaPlayerCard[K] } & { [K in keyof FmaPlayerCard & keyof FmaPlayerCardAttributes as `attr:${K}`]?: FmaPlayerCardAttributes[K] } & { [K in keyof FmaPlayerCard & keyof FmaPlayerCardAttributes as `prop:${K}`]?: FmaPlayerCard[K] } & OneOf<"name", FmaPlayerCard["name"], FmaPlayerCardAttributes["name"]> & OneOf<"team", FmaPlayerCard["team"], FmaPlayerCardAttributes["team"]>;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * FUT-style flippable player card — built for the "Equipo Ideal" feature.
             * Tap / click (or Enter / Space) flips the card on its vertical axis:
             *   - Front: tier-framed portrait, big overall, position, name, club and a
             *     compact 6-attribute strip — the classic Ultimate Team face.
             *   - Back:  the six attributes laid out as labelled gauges plus the AI's
             *     justification (`reason`) for picking this player.
             * Data-source agnostic by design: every value arrives through props, so the
             * host can feed it mock fixtures (this preview), a future stats-bearing
             * ideal-team response, or a per-player fetch — the component does not care.
             * Attributes are 0–99 (FUT scale), not the app's 0–10 statistic rating; the
             * AI is expected to emit them on the FUT scale. Tier (bronze / silver / gold
             * / icon) is derived from `overall` using FUT thresholds and drives the frame
             * colour, mirroring the ring tiers of <fma-player-card>.
             * Goalkeepers swap the outfield labels (PAC/SHO/PAS/DRI/DEF/PHY) for the GK
             * set (DIV/HAN/KIC/REF/SPD/POS) over the same six numeric slots.
             * Inherits --app-* design tokens through the shadow boundary with local
             * fallbacks, so it renders sensibly in a token-less host.
             */
            "fma-fut-card": LocalJSX.IntrinsicElements["fma-fut-card"] & JSXBase.HTMLAttributes<HTMLFmaFutCardElement>;
            /**
             * Player roster tile — used in /players list and search results.
             * Inputs map 1:1 to PlayerListItemDto from the .NET backend (and the
             * mirrored Node response): name, team, league, position, image-url,
             * rating. Anonymous and registered users see the same tile; admin
             * action affordances are exposed through the `actions` slot so this
             * component stays role-agnostic.
             * Clicking the tile emits a `playerSelected` CustomEvent with the
             * normalized payload, so the host can route to the detail page or
             * trigger any other navigation without the tile knowing about it.
             * Layout — square-ish tile (~1 : 1.15 aspect), designed for 2 columns
             * on a 360-420px mobile viewport and 3-5 columns on tablet/desktop via
             * `repeat(auto-fill, minmax(180px, 1fr))` on the host grid.
             * Design language ("Stadium control room HUD", Gridiron Neon palette
             * from DESIGN.md / frontend theme/variables.scss):
             *   - Circular player tokens with multi-layer glowing rings (ring color
             *     signals tier — bronze / silver / gold / icon) sit at the top.
             *   - Rating badge orbits the token at the 4-5 o'clock position.
             *   - Hexagonal grid backdrop + radial tier glow concentrated on the
             *     token area give the surface a premium simulator depth.
             *   - A thin tier accent stripe at the bottom edge reinforces the tier
             *     when the user scrolls a long grid.
             *   - The component reads --app-* CSS custom properties from the host
             *     so the design tokens are inherited automatically through the
             *     shadow boundary; no token duplication.
             * `league` is kept on the prop surface for forward-compat with the DTO
             * but intentionally not rendered in the tile — at 180px wide there is
             * no room for it without truncating something more important. The
             * league is still available on the player detail page.
             */
            "fma-player-card": LocalJSX.IntrinsicElements["fma-player-card"] & JSXBase.HTMLAttributes<HTMLFmaPlayerCardElement>;
        }
    }
}
