/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    /**
     * Player roster tile — used in /players list and search results.
     * Inputs map 1:1 to PlayerListItemDto from the .NET backend (and the
     * mirrored Node response): name, team, league, position, image-url,
     * rating. Anonymous and registered users see the same tile; admin
     * action affordances are exposed through the `actions` slot so this
     * component stays role-agnostic.
     * Clicking the tile emits a `playerSelected` CustomEvent with the
     * normalized payload, so the host can route to the detail page or
     * trigger any other navigation without the tile knowing about it.
     * Layout — square-ish tile (~1 : 1.15 aspect), designed for 2 columns
     * on a 360-420px mobile viewport and 3-5 columns on tablet/desktop via
     * `repeat(auto-fill, minmax(180px, 1fr))` on the host grid.
     * Design language ("Stadium control room HUD", Gridiron Neon palette
     * from DESIGN.md / frontend theme/variables.scss):
     *   - Circular player tokens with multi-layer glowing rings (ring color
     *     signals tier — bronze / silver / gold / icon) sit at the top.
     *   - Rating badge orbits the token at the 4-5 o'clock position.
     *   - Hexagonal grid backdrop + radial tier glow concentrated on the
     *     token area give the surface a premium simulator depth.
     *   - A thin tier accent stripe at the bottom edge reinforces the tier
     *     when the user scrolls a long grid.
     *   - The component reads --app-* CSS custom properties from the host
     *     so the design tokens are inherited automatically through the
     *     shadow boundary; no token duplication.
     * `league` is kept on the prop surface for forward-compat with the DTO
     * but intentionally not rendered in the tile — at 180px wide there is
     * no room for it without truncating something more important. The
     * league is still available on the player detail page.
     */
    interface FmaPlayerCard {
        /**
          * Image URL — Firebase Storage, API-Football, or manual.
         */
        "imageUrl"?: string;
        /**
          * When true, the whole tile is keyboard-interactive and emits playerSelected on click / Enter / Space. Defaults to true; flip to false for purely-display contexts (e.g. inside a pop-up).
          * @default true
         */
        "interactive": boolean;
        /**
          * Marks the tile as a manually-created player (no upstream API-Football source, therefore no statistics). When true, the rating slot is replaced by a "MANUAL" chip so users can tell the card apart from an imported player whose stats just haven't loaded yet.
          * @default false
         */
        "isManual": boolean;
        /**
          * League name. Accepted for DTO parity, not displayed in the tile.
         */
        "league"?: string;
        /**
          * Player display name (required).
         */
        "name": string;
        /**
          * Player identifier — emitted with playerSelected for the host to route.
         */
        "playerId"?: string;
        /**
          * Position label (Goalkeeper, Defender, Midfielder, Attacker).
         */
        "position"?: string;
        /**
          * Overall rating (0–10, decimal). Renders the orbital badge if present.
         */
        "rating"?: number;
        /**
          * Team name (required).
         */
        "team": string;
    }
}
export interface FmaPlayerCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFmaPlayerCardElement;
}
declare global {
    interface HTMLFmaPlayerCardElementEventMap {
        "playerSelected": { playerId?: string; name: string };
    }
    /**
     * Player roster tile — used in /players list and search results.
     * Inputs map 1:1 to PlayerListItemDto from the .NET backend (and the
     * mirrored Node response): name, team, league, position, image-url,
     * rating. Anonymous and registered users see the same tile; admin
     * action affordances are exposed through the `actions` slot so this
     * component stays role-agnostic.
     * Clicking the tile emits a `playerSelected` CustomEvent with the
     * normalized payload, so the host can route to the detail page or
     * trigger any other navigation without the tile knowing about it.
     * Layout — square-ish tile (~1 : 1.15 aspect), designed for 2 columns
     * on a 360-420px mobile viewport and 3-5 columns on tablet/desktop via
     * `repeat(auto-fill, minmax(180px, 1fr))` on the host grid.
     * Design language ("Stadium control room HUD", Gridiron Neon palette
     * from DESIGN.md / frontend theme/variables.scss):
     *   - Circular player tokens with multi-layer glowing rings (ring color
     *     signals tier — bronze / silver / gold / icon) sit at the top.
     *   - Rating badge orbits the token at the 4-5 o'clock position.
     *   - Hexagonal grid backdrop + radial tier glow concentrated on the
     *     token area give the surface a premium simulator depth.
     *   - A thin tier accent stripe at the bottom edge reinforces the tier
     *     when the user scrolls a long grid.
     *   - The component reads --app-* CSS custom properties from the host
     *     so the design tokens are inherited automatically through the
     *     shadow boundary; no token duplication.
     * `league` is kept on the prop surface for forward-compat with the DTO
     * but intentionally not rendered in the tile — at 180px wide there is
     * no room for it without truncating something more important. The
     * league is still available on the player detail page.
     */
    interface HTMLFmaPlayerCardElement extends Components.FmaPlayerCard, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFmaPlayerCardElementEventMap>(type: K, listener: (this: HTMLFmaPlayerCardElement, ev: FmaPlayerCardCustomEvent<HTMLFmaPlayerCardElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFmaPlayerCardElementEventMap>(type: K, listener: (this: HTMLFmaPlayerCardElement, ev: FmaPlayerCardCustomEvent<HTMLFmaPlayerCardElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFmaPlayerCardElement: {
        prototype: HTMLFmaPlayerCardElement;
        new (): HTMLFmaPlayerCardElement;
    };
    interface HTMLElementTagNameMap {
        "fma-player-card": HTMLFmaPlayerCardElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}` | `prop:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K | `prop:${K}`]?: never } | { [P in `prop:${K}`]: PropT } & { [P in K | `attr:${K}`]?: never };

    /**
     * Player roster tile — used in /players list and search results.
     * Inputs map 1:1 to PlayerListItemDto from the .NET backend (and the
     * mirrored Node response): name, team, league, position, image-url,
     * rating. Anonymous and registered users see the same tile; admin
     * action affordances are exposed through the `actions` slot so this
     * component stays role-agnostic.
     * Clicking the tile emits a `playerSelected` CustomEvent with the
     * normalized payload, so the host can route to the detail page or
     * trigger any other navigation without the tile knowing about it.
     * Layout — square-ish tile (~1 : 1.15 aspect), designed for 2 columns
     * on a 360-420px mobile viewport and 3-5 columns on tablet/desktop via
     * `repeat(auto-fill, minmax(180px, 1fr))` on the host grid.
     * Design language ("Stadium control room HUD", Gridiron Neon palette
     * from DESIGN.md / frontend theme/variables.scss):
     *   - Circular player tokens with multi-layer glowing rings (ring color
     *     signals tier — bronze / silver / gold / icon) sit at the top.
     *   - Rating badge orbits the token at the 4-5 o'clock position.
     *   - Hexagonal grid backdrop + radial tier glow concentrated on the
     *     token area give the surface a premium simulator depth.
     *   - A thin tier accent stripe at the bottom edge reinforces the tier
     *     when the user scrolls a long grid.
     *   - The component reads --app-* CSS custom properties from the host
     *     so the design tokens are inherited automatically through the
     *     shadow boundary; no token duplication.
     * `league` is kept on the prop surface for forward-compat with the DTO
     * but intentionally not rendered in the tile — at 180px wide there is
     * no room for it without truncating something more important. The
     * league is still available on the player detail page.
     */
    interface FmaPlayerCard {
        /**
          * Image URL — Firebase Storage, API-Football, or manual.
         */
        "imageUrl"?: string;
        /**
          * When true, the whole tile is keyboard-interactive and emits playerSelected on click / Enter / Space. Defaults to true; flip to false for purely-display contexts (e.g. inside a pop-up).
          * @default true
         */
        "interactive"?: boolean;
        /**
          * Marks the tile as a manually-created player (no upstream API-Football source, therefore no statistics). When true, the rating slot is replaced by a "MANUAL" chip so users can tell the card apart from an imported player whose stats just haven't loaded yet.
          * @default false
         */
        "isManual"?: boolean;
        /**
          * League name. Accepted for DTO parity, not displayed in the tile.
         */
        "league"?: string;
        /**
          * Player display name (required).
         */
        "name": string;
        "onPlayerSelected"?: (event: FmaPlayerCardCustomEvent<{ playerId?: string; name: string }>) => void;
        /**
          * Player identifier — emitted with playerSelected for the host to route.
         */
        "playerId"?: string;
        /**
          * Position label (Goalkeeper, Defender, Midfielder, Attacker).
         */
        "position"?: string;
        /**
          * Overall rating (0–10, decimal). Renders the orbital badge if present.
         */
        "rating"?: number;
        /**
          * Team name (required).
         */
        "team": string;
    }

    interface FmaPlayerCardAttributes {
        "name": string;
        "team": string;
        "league": string;
        "position": string;
        "imageUrl": string;
        "rating": number;
        "playerId": string;
        "isManual": boolean;
        "interactive": boolean;
    }

    interface IntrinsicElements {
        "fma-player-card": Omit<FmaPlayerCard, keyof FmaPlayerCardAttributes> & { [K in keyof FmaPlayerCard & keyof FmaPlayerCardAttributes]?: FmaPlayerCard[K] } & { [K in keyof FmaPlayerCard & keyof FmaPlayerCardAttributes as `attr:${K}`]?: FmaPlayerCardAttributes[K] } & { [K in keyof FmaPlayerCard & keyof FmaPlayerCardAttributes as `prop:${K}`]?: FmaPlayerCard[K] } & OneOf<"name", FmaPlayerCard["name"], FmaPlayerCardAttributes["name"]> & OneOf<"team", FmaPlayerCard["team"], FmaPlayerCardAttributes["team"]>;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * Player roster tile — used in /players list and search results.
             * Inputs map 1:1 to PlayerListItemDto from the .NET backend (and the
             * mirrored Node response): name, team, league, position, image-url,
             * rating. Anonymous and registered users see the same tile; admin
             * action affordances are exposed through the `actions` slot so this
             * component stays role-agnostic.
             * Clicking the tile emits a `playerSelected` CustomEvent with the
             * normalized payload, so the host can route to the detail page or
             * trigger any other navigation without the tile knowing about it.
             * Layout — square-ish tile (~1 : 1.15 aspect), designed for 2 columns
             * on a 360-420px mobile viewport and 3-5 columns on tablet/desktop via
             * `repeat(auto-fill, minmax(180px, 1fr))` on the host grid.
             * Design language ("Stadium control room HUD", Gridiron Neon palette
             * from DESIGN.md / frontend theme/variables.scss):
             *   - Circular player tokens with multi-layer glowing rings (ring color
             *     signals tier — bronze / silver / gold / icon) sit at the top.
             *   - Rating badge orbits the token at the 4-5 o'clock position.
             *   - Hexagonal grid backdrop + radial tier glow concentrated on the
             *     token area give the surface a premium simulator depth.
             *   - A thin tier accent stripe at the bottom edge reinforces the tier
             *     when the user scrolls a long grid.
             *   - The component reads --app-* CSS custom properties from the host
             *     so the design tokens are inherited automatically through the
             *     shadow boundary; no token duplication.
             * `league` is kept on the prop surface for forward-compat with the DTO
             * but intentionally not rendered in the tile — at 180px wide there is
             * no room for it without truncating something more important. The
             * league is still available on the player detail page.
             */
            "fma-player-card": LocalJSX.IntrinsicElements["fma-player-card"] & JSXBase.HTMLAttributes<HTMLFmaPlayerCardElement>;
        }
    }
}
