/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    /**
     * Player summary card — used in /players list and search results.
     * Inputs map 1:1 to PlayerListItemDto from the .NET backend (and the
     * mirrored Node response): name, team, league, position, image-url,
     * rating. Anonymous and registered users see the same component; admin
     * action affordances are exposed through the `actions` slot so this
     * component stays role-agnostic.
     * Clicking the card emits a `playerSelected` CustomEvent with the
     * normalized payload, so the host can route to the detail page or
     * trigger any other navigation without the card knowing about it.
     * Design language (Gridiron Neon, see DESIGN.md / frontend
     * theme/variables.scss): glass surface gradient, neon-green primary on
     * focus/hover, rating as a tier-coloured pill (bronze/silver/gold/icon).
     * The component reads --app-* CSS custom properties from the host so the
     * design tokens are inherited automatically; no token duplication.
     */
    interface FmaPlayerCard {
        /**
          * Image URL — Firebase Storage, API-Football, or manual.
         */
        "imageUrl"?: string;
        /**
          * When true, the whole card is keyboard-interactive and emits playerSelected on click / Enter / Space. Defaults to true; flip to false for purely-display contexts (e.g. inside a pop-up).
          * @default true
         */
        "interactive": boolean;
        /**
          * League name (required).
         */
        "league": string;
        /**
          * Player display name (required).
         */
        "name": string;
        /**
          * Player identifier — emitted with playerSelected for the host to route.
         */
        "playerId"?: string;
        /**
          * Position label (Goalkeeper, Defender, Midfielder, Attacker).
         */
        "position"?: string;
        /**
          * Overall rating (0–10, decimal). Renders the tier pill if present.
         */
        "rating"?: number;
        /**
          * Team name (required).
         */
        "team": string;
    }
}
export interface FmaPlayerCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFmaPlayerCardElement;
}
declare global {
    interface HTMLFmaPlayerCardElementEventMap {
        "playerSelected": { playerId?: string; name: string };
    }
    /**
     * Player summary card — used in /players list and search results.
     * Inputs map 1:1 to PlayerListItemDto from the .NET backend (and the
     * mirrored Node response): name, team, league, position, image-url,
     * rating. Anonymous and registered users see the same component; admin
     * action affordances are exposed through the `actions` slot so this
     * component stays role-agnostic.
     * Clicking the card emits a `playerSelected` CustomEvent with the
     * normalized payload, so the host can route to the detail page or
     * trigger any other navigation without the card knowing about it.
     * Design language (Gridiron Neon, see DESIGN.md / frontend
     * theme/variables.scss): glass surface gradient, neon-green primary on
     * focus/hover, rating as a tier-coloured pill (bronze/silver/gold/icon).
     * The component reads --app-* CSS custom properties from the host so the
     * design tokens are inherited automatically; no token duplication.
     */
    interface HTMLFmaPlayerCardElement extends Components.FmaPlayerCard, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFmaPlayerCardElementEventMap>(type: K, listener: (this: HTMLFmaPlayerCardElement, ev: FmaPlayerCardCustomEvent<HTMLFmaPlayerCardElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFmaPlayerCardElementEventMap>(type: K, listener: (this: HTMLFmaPlayerCardElement, ev: FmaPlayerCardCustomEvent<HTMLFmaPlayerCardElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFmaPlayerCardElement: {
        prototype: HTMLFmaPlayerCardElement;
        new (): HTMLFmaPlayerCardElement;
    };
    interface HTMLElementTagNameMap {
        "fma-player-card": HTMLFmaPlayerCardElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}` | `prop:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K | `prop:${K}`]?: never } | { [P in `prop:${K}`]: PropT } & { [P in K | `attr:${K}`]?: never };

    /**
     * Player summary card — used in /players list and search results.
     * Inputs map 1:1 to PlayerListItemDto from the .NET backend (and the
     * mirrored Node response): name, team, league, position, image-url,
     * rating. Anonymous and registered users see the same component; admin
     * action affordances are exposed through the `actions` slot so this
     * component stays role-agnostic.
     * Clicking the card emits a `playerSelected` CustomEvent with the
     * normalized payload, so the host can route to the detail page or
     * trigger any other navigation without the card knowing about it.
     * Design language (Gridiron Neon, see DESIGN.md / frontend
     * theme/variables.scss): glass surface gradient, neon-green primary on
     * focus/hover, rating as a tier-coloured pill (bronze/silver/gold/icon).
     * The component reads --app-* CSS custom properties from the host so the
     * design tokens are inherited automatically; no token duplication.
     */
    interface FmaPlayerCard {
        /**
          * Image URL — Firebase Storage, API-Football, or manual.
         */
        "imageUrl"?: string;
        /**
          * When true, the whole card is keyboard-interactive and emits playerSelected on click / Enter / Space. Defaults to true; flip to false for purely-display contexts (e.g. inside a pop-up).
          * @default true
         */
        "interactive"?: boolean;
        /**
          * League name (required).
         */
        "league": string;
        /**
          * Player display name (required).
         */
        "name": string;
        "onPlayerSelected"?: (event: FmaPlayerCardCustomEvent<{ playerId?: string; name: string }>) => void;
        /**
          * Player identifier — emitted with playerSelected for the host to route.
         */
        "playerId"?: string;
        /**
          * Position label (Goalkeeper, Defender, Midfielder, Attacker).
         */
        "position"?: string;
        /**
          * Overall rating (0–10, decimal). Renders the tier pill if present.
         */
        "rating"?: number;
        /**
          * Team name (required).
         */
        "team": string;
    }

    interface FmaPlayerCardAttributes {
        "name": string;
        "team": string;
        "league": string;
        "position": string;
        "imageUrl": string;
        "rating": number;
        "playerId": string;
        "interactive": boolean;
    }

    interface IntrinsicElements {
        "fma-player-card": Omit<FmaPlayerCard, keyof FmaPlayerCardAttributes> & { [K in keyof FmaPlayerCard & keyof FmaPlayerCardAttributes]?: FmaPlayerCard[K] } & { [K in keyof FmaPlayerCard & keyof FmaPlayerCardAttributes as `attr:${K}`]?: FmaPlayerCardAttributes[K] } & { [K in keyof FmaPlayerCard & keyof FmaPlayerCardAttributes as `prop:${K}`]?: FmaPlayerCard[K] } & OneOf<"name", FmaPlayerCard["name"], FmaPlayerCardAttributes["name"]> & OneOf<"team", FmaPlayerCard["team"], FmaPlayerCardAttributes["team"]> & OneOf<"league", FmaPlayerCard["league"], FmaPlayerCardAttributes["league"]>;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * Player summary card — used in /players list and search results.
             * Inputs map 1:1 to PlayerListItemDto from the .NET backend (and the
             * mirrored Node response): name, team, league, position, image-url,
             * rating. Anonymous and registered users see the same component; admin
             * action affordances are exposed through the `actions` slot so this
             * component stays role-agnostic.
             * Clicking the card emits a `playerSelected` CustomEvent with the
             * normalized payload, so the host can route to the detail page or
             * trigger any other navigation without the card knowing about it.
             * Design language (Gridiron Neon, see DESIGN.md / frontend
             * theme/variables.scss): glass surface gradient, neon-green primary on
             * focus/hover, rating as a tier-coloured pill (bronze/silver/gold/icon).
             * The component reads --app-* CSS custom properties from the host so the
             * design tokens are inherited automatically; no token duplication.
             */
            "fma-player-card": LocalJSX.IntrinsicElements["fma-player-card"] & JSXBase.HTMLAttributes<HTMLFmaPlayerCardElement>;
        }
    }
}
