// <auto-generated />
using System;
using FootballManagerApp.Players.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FootballManagerApp.Players.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PlayersDbContext))]
    [Migration("20260512203223_InitialPlayersSchema")]
    partial class InitialPlayersSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FootballManagerApp.Players.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ApiFootballId")
                        .HasColumnType("integer");

                    b.Property<string>("BirthCountry")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BirthPlace")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Height")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ImageSource")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("Injured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("League")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nationality")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Position")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ShirtNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Weight")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ApiFootballId")
                        .IsUnique()
                        .HasFilter("\"ApiFootballId\" IS NOT NULL");

                    b.ToTable("Players", (string)null);
                });

            modelBuilder.Entity("FootballManagerApp.Players.Domain.Entities.PlayerStatistics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Appearances")
                        .HasColumnType("integer");

                    b.Property<int>("Assists")
                        .HasColumnType("integer");

                    b.Property<bool>("Captain")
                        .HasColumnType("boolean");

                    b.Property<int>("DribblesAttempts")
                        .HasColumnType("integer");

                    b.Property<int>("DribblesSuccess")
                        .HasColumnType("integer");

                    b.Property<int>("DuelsTotal")
                        .HasColumnType("integer");

                    b.Property<int>("DuelsWon")
                        .HasColumnType("integer");

                    b.Property<int>("FoulsCommitted")
                        .HasColumnType("integer");

                    b.Property<int>("FoulsDrawn")
                        .HasColumnType("integer");

                    b.Property<int>("Goals")
                        .HasColumnType("integer");

                    b.Property<int>("GoalsConceded")
                        .HasColumnType("integer");

                    b.Property<int>("GoalsSaved")
                        .HasColumnType("integer");

                    b.Property<int>("Interceptions")
                        .HasColumnType("integer");

                    b.Property<string>("LeagueCountry")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("LeagueId")
                        .HasColumnType("integer");

                    b.Property<string>("LeagueLogo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("LeagueName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Lineups")
                        .HasColumnType("integer");

                    b.Property<int>("MinutesPlayed")
                        .HasColumnType("integer");

                    b.Property<int>("PassesAccuracy")
                        .HasColumnType("integer");

                    b.Property<int>("PassesKey")
                        .HasColumnType("integer");

                    b.Property<int>("PassesTotal")
                        .HasColumnType("integer");

                    b.Property<int>("PenaltyMissed")
                        .HasColumnType("integer");

                    b.Property<int>("PenaltySaved")
                        .HasColumnType("integer");

                    b.Property<int>("PenaltyScored")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Position")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("Rating")
                        .HasPrecision(6, 4)
                        .HasColumnType("numeric(6,4)");

                    b.Property<int>("RedCards")
                        .HasColumnType("integer");

                    b.Property<int>("Season")
                        .HasColumnType("integer");

                    b.Property<int>("ShotsOnTarget")
                        .HasColumnType("integer");

                    b.Property<int>("ShotsTotal")
                        .HasColumnType("integer");

                    b.Property<int>("SubstitutesBench")
                        .HasColumnType("integer");

                    b.Property<int>("SubstitutesIn")
                        .HasColumnType("integer");

                    b.Property<int>("SubstitutesOut")
                        .HasColumnType("integer");

                    b.Property<int>("TacklesBlocks")
                        .HasColumnType("integer");

                    b.Property<int>("TacklesTotal")
                        .HasColumnType("integer");

                    b.Property<int?>("TeamId")
                        .HasColumnType("integer");

                    b.Property<string>("TeamLogo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TeamName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("YellowCards")
                        .HasColumnType("integer");

                    b.Property<int>("YellowRedCards")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "Season", "LeagueId", "TeamId")
                        .IsUnique();

                    b.ToTable("PlayerStatistics", (string)null);
                });

            modelBuilder.Entity("FootballManagerApp.Players.Domain.Entities.Player", b =>
                {
                    b.OwnsOne("FootballManagerApp.Shared.ValueObjects.Geolocation", "ClientGeolocation", b1 =>
                        {
                            b1.Property<Guid>("PlayerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("ClientCity");

                            b1.Property<string>("Country")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("ClientCountry");

                            b1.Property<decimal>("Lat")
                                .HasPrecision(10, 8)
                                .HasColumnType("numeric(10,8)")
                                .HasColumnName("ClientLat");

                            b1.Property<decimal>("Lng")
                                .HasPrecision(11, 8)
                                .HasColumnType("numeric(11,8)")
                                .HasColumnName("ClientLng");

                            b1.HasKey("PlayerId");

                            b1.ToTable("Players");

                            b1.WithOwner()
                                .HasForeignKey("PlayerId");
                        });

                    b.OwnsOne("FootballManagerApp.Shared.ValueObjects.Geolocation", "PlayerGeolocation", b1 =>
                        {
                            b1.Property<Guid>("PlayerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("PlayerCity");

                            b1.Property<string>("Country")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("PlayerCountry");

                            b1.Property<decimal>("Lat")
                                .HasPrecision(10, 8)
                                .HasColumnType("numeric(10,8)")
                                .HasColumnName("PlayerLat");

                            b1.Property<decimal>("Lng")
                                .HasPrecision(11, 8)
                                .HasColumnType("numeric(11,8)")
                                .HasColumnName("PlayerLng");

                            b1.HasKey("PlayerId");

                            b1.ToTable("Players");

                            b1.WithOwner()
                                .HasForeignKey("PlayerId");
                        });

                    b.Navigation("ClientGeolocation");

                    b.Navigation("PlayerGeolocation");
                });

            modelBuilder.Entity("FootballManagerApp.Players.Domain.Entities.PlayerStatistics", b =>
                {
                    b.HasOne("FootballManagerApp.Players.Domain.Entities.Player", null)
                        .WithMany("Statistics")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FootballManagerApp.Players.Domain.Entities.Player", b =>
                {
                    b.Navigation("Statistics");
                });
#pragma warning restore 612, 618
        }
    }
}
